<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\RelatedItemsManagement\Services;

class RelatedItemsManagementService extends \EbaySdk\Api\RelatedItemsManagement\Services\RelatedItemsManagementBaseService
{
    const API_VERSION = '1.0.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\CreateBundlesRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\CreateBundlesResponse
     */
    public function createBundles(\EbaySdk\Api\RelatedItemsManagement\Types\CreateBundlesRequest $request)
    {
        return $this->callOperation('createBundles', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\CreateBundlesResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\FindBundlesRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\FindBundlesResponse
     */
    public function findBundles(\EbaySdk\Api\RelatedItemsManagement\Types\FindBundlesRequest $request)
    {
        return $this->callOperation('findBundles', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\FindBundlesResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\GetBundlesRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\GetBundlesResponse
     */
    public function getBundles(\EbaySdk\Api\RelatedItemsManagement\Types\GetBundlesRequest $request)
    {
        return $this->callOperation('getBundles', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\GetBundlesResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundlesRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundlesResponse
     */
    public function updateBundles(\EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundlesRequest $request)
    {
        return $this->callOperation('updateBundles', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundlesResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundleStatusRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundleStatusResponse
     */
    public function updateBundleStatus(\EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundleStatusRequest $request)
    {
        return $this->callOperation('updateBundleStatus', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\UpdateBundleStatusResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\DeleteBundlesRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\DeleteBundlesResponse
     */
    public function deleteBundles(\EbaySdk\Api\RelatedItemsManagement\Types\DeleteBundlesRequest $request)
    {
        return $this->callOperation('deleteBundles', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\DeleteBundlesResponse');
    }

    /**
     * @param \EbaySdk\Api\RelatedItemsManagement\Types\GetVersionRequest $request
     * @return \EbaySdk\Api\RelatedItemsManagement\Types\GetVersionResponse
     */
    public function getVersion(\EbaySdk\Api\RelatedItemsManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperation('getVersion', $request, '\EbaySdk\Api\RelatedItemsManagement\Types\GetVersionResponse');
    }
}
