<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Browse\Enums;

/**
 *
 */
class DeliveryOptionsEnum
{
    const C_DIGITAL_DELIVERY = 'DIGITAL_DELIVERY';
    const C_IN_STORE_PICKUP = 'IN_STORE_PICKUP';
    const C_PICKUP_DROP_OFF = 'PICKUP_DROP_OFF';
    const C_SELLER_ARRANGED_LOCAL_PICKUP = 'SELLER_ARRANGED_LOCAL_PICKUP';
    const C_SHIP_TO_HOME = 'SHIP_TO_HOME';
}
