<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Browse\Enums;

/**
 *
 */
class ValueTypeEnum
{
    const C_STRING = 'STRING';
    const C_STRING_ARRAY = 'STRING_ARRAY';
}
