<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Product\Types;

/**
 *
 * @property \EbaySdk\Product\Types\ProductIdentifier $productIdentifier
 * @property \EbaySdk\Product\Types\PaginationInput $paginationInput
 * @property \EbaySdk\Product\Types\PropertyValue[] $applicationPropertyFilter
 * @property string[] $dataset
 * @property \EbaySdk\Product\Types\CompatibilitySort[] $sortOrder
 * @property \EbaySdk\Product\Types\ProductStatus $disabledProductFilter
 * @property string[] $datasetPropertyName
 */
class GetProductCompatibilitiesRequest extends \EbaySdk\Api\Product\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'productIdentifier' => [
            'type' => 'EbaySdk\Product\Types\ProductIdentifier',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'productIdentifier'
        ],
        'paginationInput' => [
            'type' => 'EbaySdk\Product\Types\PaginationInput',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationInput'
        ],
        'applicationPropertyFilter' => [
            'type' => 'EbaySdk\Product\Types\PropertyValue',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'applicationPropertyFilter'
        ],
        'dataset' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'dataset'
        ],
        'sortOrder' => [
            'type' => 'EbaySdk\Product\Types\CompatibilitySort',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'sortOrder'
        ],
        'disabledProductFilter' => [
            'type' => 'EbaySdk\Product\Types\ProductStatus',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'disabledProductFilter'
        ],
        'datasetPropertyName' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'datasetPropertyName'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'getProductCompatibilitiesRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
