<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Fulfillment\Enums;

/**
 *
 */
class CancelRequestStateEnum
{
    const C_COMPLETED = 'COMPLETED';
    const C_REJECTED = 'REJECTED';
    const C_REQUESTED = 'REQUESTED';
}
