<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Fulfillment\Enums;

/**
 *
 */
class PaymentModeTypeEnum
{
    const C_OFF_LINE = 'OFF_LINE';
    const C_ONLINE = 'ONLINE';
}
