<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\HalfFinding\Types;

/**
 *
 * @property \EbaySdk\HalfFinding\Types\ProductIDType $productID
 * @property \EbaySdk\HalfFinding\Types\PaginationInputType $paginationInput
 * @property \EbaySdk\HalfFinding\Types\ItemFilter[] $itemFilter
 * @property \EbaySdk\HalfFinding\Types\SortByType $sortBy
 */
class FindItemsRequest extends \EbaySdk\Api\HalfFinding\Types\BaseRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'productID' => [
            'type' => 'EbaySdk\HalfFinding\Types\ProductIDType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'productID'
        ],
        'paginationInput' => [
            'type' => 'EbaySdk\HalfFinding\Types\PaginationInputType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationInput'
        ],
        'itemFilter' => [
            'type' => 'EbaySdk\HalfFinding\Types\ItemFilter',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'itemFilter'
        ],
        'sortBy' => [
            'type' => 'EbaySdk\HalfFinding\Types\SortByType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sortBy'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/half/v1/services"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'findHalfItemsRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
