<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\HalfFinding\Types;

/**
 *
 * @property \EbaySdk\HalfFinding\Types\PaginationOutputType $paginationOutput
 * @property \EbaySdk\HalfFinding\Types\HalfCatalogProductType $product
 */
class FindItemsResponse extends \EbaySdk\Api\HalfFinding\Types\BaseResponse
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'paginationOutput' => [
            'type' => 'EbaySdk\HalfFinding\Types\PaginationOutputType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationOutput'
        ],
        'product' => [
            'type' => 'EbaySdk\HalfFinding\Types\HalfCatalogProductType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'product'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/half/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
