<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\PostOrder\Types;

/**
 *
 * @property \EbaySdk\PostOrder\Types\EstimatedRefundInfoType $refundInfo
 * @property \EbaySdk\PostOrder\Types\EstimatedShippingInfoType $returnShippingCostInfo
 */
class GetEstimateResponse extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'refundInfo' => [
            'type' => 'EbaySdk\PostOrder\Types\EstimatedRefundInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'refundInfo'
        ],
        'returnShippingCostInfo' => [
            'type' => 'EbaySdk\PostOrder\Types\EstimatedShippingInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnShippingCostInfo'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
