<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\PostOrder\Types;

/**
 *
 * @property \EbaySdk\Api\PostOrder\Types\RuleActionDetailType $actionDetail
 * @property \EbaySdk\Api\PostOrder\Types\RuleConditionDetailType[] $condition
 * @property \EbaySdk\Api\PostOrder\Types\RuleSummaryType $ruleSummary
 */
class RuleDetailType extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'actionDetail' => [
            'type' => 'EbaySdk\Api\PostOrder\Types\RuleActionDetailType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'actionDetail'
        ],
        'condition' => [
            'type' => 'EbaySdk\Api\PostOrder\Types\RuleConditionDetailType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'condition'
        ],
        'ruleSummary' => [
            'type' => 'EbaySdk\Api\PostOrder\Types\RuleSummaryType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ruleSummary'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[\Plenty\Modules\Market\Ebay\Api\Types\BaseType::class], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
