<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Trading\Enums;

/**
 *
 */
class NotificationEventPropertyNameCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_TIME_LEFT = 'TimeLeft';
}
