<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\ReturnManagement\Services;

class ReturnManagementService extends \EbaySdk\Api\ReturnManagement\Services\ReturnManagementBaseService
{
    const API_VERSION = '1.1.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\GetVersionRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\GetVersionResponse
     */
    public function getVersion(\EbaySdk\Api\ReturnManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperation('getVersion', $request, '\EbaySdk\Api\ReturnManagement\Types\GetVersionResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\GetUserReturnsRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\GetUserReturnsResponse
     */
    public function getUserReturns(\EbaySdk\Api\ReturnManagement\Types\GetUserReturnsRequest $request)
    {
        return $this->callOperation('getUserReturns', $request, '\EbaySdk\Api\ReturnManagement\Types\GetUserReturnsResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\GetReturnDetailRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\GetReturnDetailResponse
     */
    public function getReturnDetail(\EbaySdk\Api\ReturnManagement\Types\GetReturnDetailRequest $request)
    {
        return $this->callOperation('getReturnDetail', $request, '\EbaySdk\Api\ReturnManagement\Types\GetReturnDetailResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\GetActivityOptionsRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\GetActivityOptionsResponse
     */
    public function getActivityOptions(\EbaySdk\Api\ReturnManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->callOperation('getActivityOptions', $request, '\EbaySdk\Api\ReturnManagement\Types\GetActivityOptionsResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\IssueRefundRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\IssueRefundResponse
     */
    public function issueRefund(\EbaySdk\Api\ReturnManagement\Types\IssueRefundRequest $request)
    {
        return $this->callOperation('issueRefund', $request, '\EbaySdk\Api\ReturnManagement\Types\IssueRefundResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\ProvideSellerInfoRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\ProvideSellerInfoResponse
     */
    public function provideSellerInfo(\EbaySdk\Api\ReturnManagement\Types\ProvideSellerInfoRequest $request)
    {
        return $this->callOperation('provideSellerInfo', $request, '\EbaySdk\Api\ReturnManagement\Types\ProvideSellerInfoResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\GetReturnMetadataRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\GetReturnMetadataResponse
     */
    public function getReturnMetadata(\EbaySdk\Api\ReturnManagement\Types\GetReturnMetadataRequest $request)
    {
        return $this->callOperation('getReturnMetadata', $request, '\EbaySdk\Api\ReturnManagement\Types\GetReturnMetadataResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\ProvideTrackingInfoRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\ProvideTrackingInfoResponse
     */
    public function provideTrackingInfo(\EbaySdk\Api\ReturnManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->callOperation('provideTrackingInfo', $request, '\EbaySdk\Api\ReturnManagement\Types\ProvideTrackingInfoResponse');
    }

    /**
     * @param \EbaySdk\Api\ReturnManagement\Types\SetItemAsReceivedRequest $request
     * @return \EbaySdk\Api\ReturnManagement\Types\SetItemAsReceivedResponse
     */
    public function setItemAsReceived(\EbaySdk\Api\ReturnManagement\Types\SetItemAsReceivedRequest $request)
    {
        return $this->callOperation('setItemAsReceived', $request, '\EbaySdk\Api\ReturnManagement\Types\SetItemAsReceivedResponse');
    }
}
