<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\ProductMetadata\Types;

/**
 *
 * @property string $metadataVersion
 * @property \EbaySdk\ProductMetadata\Types\PropertyValue[] $propertyValues
 * @property \EbaySdk\ProductMetadata\Types\PropertyNameValue $propertyValuesTree
 * @property boolean $treeFormat
 */
class GetCompatibilitySearchValuesResponse extends \EbaySdk\Api\ProductMetadata\Types\BaseServiceResponse
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'metadataVersion' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'metadataVersion'
        ],
        'propertyValues' => [
            'type' => 'EbaySdk\ProductMetadata\Types\PropertyValue',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'propertyValues'
        ],
        'propertyValuesTree' => [
            'type' => 'EbaySdk\ProductMetadata\Types\PropertyNameValue',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'propertyValuesTree'
        ],
        'treeFormat' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'treeFormat'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
