<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Trading\Services;

class TradingService extends \EbaySdk\Api\Trading\Services\TradingBaseService
{
    const API_VERSION = '1019';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddDisputeRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddDisputeResponseType
     */
    public function addDispute(\EbaySdk\Api\Trading\Types\AddDisputeRequestType $request)
    {
        return $this->callOperation('AddDispute', $request, '\EbaySdk\Api\Trading\Types\AddDisputeResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddDisputeResponseRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddDisputeResponseResponseType
     */
    public function addDisputeResponse(\EbaySdk\Api\Trading\Types\AddDisputeResponseRequestType $request)
    {
        return $this->callOperation('AddDisputeResponse', $request, '\EbaySdk\Api\Trading\Types\AddDisputeResponseResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddFixedPriceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddFixedPriceItemResponseType
     */
    public function addFixedPriceItem(\EbaySdk\Api\Trading\Types\AddFixedPriceItemRequestType $request)
    {
        return $this->callOperation('AddFixedPriceItem', $request, '\EbaySdk\Api\Trading\Types\AddFixedPriceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddItemResponseType
     */
    public function addItem(\EbaySdk\Api\Trading\Types\AddItemRequestType $request)
    {
        return $this->callOperation('AddItem', $request, '\EbaySdk\Api\Trading\Types\AddItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddItemFromSellingManagerTemplateRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddItemFromSellingManagerTemplateResponseType
     */
    public function addItemFromSellingManagerTemplate(\EbaySdk\Api\Trading\Types\AddItemFromSellingManagerTemplateRequestType $request)
    {
        return $this->callOperation('AddItemFromSellingManagerTemplate', $request, '\EbaySdk\Api\Trading\Types\AddItemFromSellingManagerTemplateResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddItemsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddItemsResponseType
     */
    public function addItems(\EbaySdk\Api\Trading\Types\AddItemsRequestType $request)
    {
        return $this->callOperation('AddItems', $request, '\EbaySdk\Api\Trading\Types\AddItemsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddMemberMessageAAQToPartnerRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddMemberMessageAAQToPartnerResponseType
     */
    public function addMemberMessageAAQToPartner(\EbaySdk\Api\Trading\Types\AddMemberMessageAAQToPartnerRequestType $request)
    {
        return $this->callOperation('AddMemberMessageAAQToPartner', $request, '\EbaySdk\Api\Trading\Types\AddMemberMessageAAQToPartnerResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddMemberMessageRTQRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddMemberMessageRTQResponseType
     */
    public function addMemberMessageRTQ(\EbaySdk\Api\Trading\Types\AddMemberMessageRTQRequestType $request)
    {
        return $this->callOperation('AddMemberMessageRTQ', $request, '\EbaySdk\Api\Trading\Types\AddMemberMessageRTQResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddMemberMessagesAAQToBidderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddMemberMessagesAAQToBidderResponseType
     */
    public function addMemberMessagesAAQToBidder(\EbaySdk\Api\Trading\Types\AddMemberMessagesAAQToBidderRequestType $request)
    {
        return $this->callOperation('AddMemberMessagesAAQToBidder', $request, '\EbaySdk\Api\Trading\Types\AddMemberMessagesAAQToBidderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddOrderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddOrderResponseType
     */
    public function addOrder(\EbaySdk\Api\Trading\Types\AddOrderRequestType $request)
    {
        return $this->callOperation('AddOrder', $request, '\EbaySdk\Api\Trading\Types\AddOrderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddSecondChanceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddSecondChanceItemResponseType
     */
    public function addSecondChanceItem(\EbaySdk\Api\Trading\Types\AddSecondChanceItemRequestType $request)
    {
        return $this->callOperation('AddSecondChanceItem', $request, '\EbaySdk\Api\Trading\Types\AddSecondChanceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddSellingManagerInventoryFolderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddSellingManagerInventoryFolderResponseType
     */
    public function addSellingManagerInventoryFolder(\EbaySdk\Api\Trading\Types\AddSellingManagerInventoryFolderRequestType $request)
    {
        return $this->callOperation('AddSellingManagerInventoryFolder', $request, '\EbaySdk\Api\Trading\Types\AddSellingManagerInventoryFolderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddSellingManagerProductRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddSellingManagerProductResponseType
     */
    public function addSellingManagerProduct(\EbaySdk\Api\Trading\Types\AddSellingManagerProductRequestType $request)
    {
        return $this->callOperation('AddSellingManagerProduct', $request, '\EbaySdk\Api\Trading\Types\AddSellingManagerProductResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddSellingManagerTemplateRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddSellingManagerTemplateResponseType
     */
    public function addSellingManagerTemplate(\EbaySdk\Api\Trading\Types\AddSellingManagerTemplateRequestType $request)
    {
        return $this->callOperation('AddSellingManagerTemplate', $request, '\EbaySdk\Api\Trading\Types\AddSellingManagerTemplateResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddToItemDescriptionRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddToItemDescriptionResponseType
     */
    public function addToItemDescription(\EbaySdk\Api\Trading\Types\AddToItemDescriptionRequestType $request)
    {
        return $this->callOperation('AddToItemDescription', $request, '\EbaySdk\Api\Trading\Types\AddToItemDescriptionResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddToWatchListRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddToWatchListResponseType
     */
    public function addToWatchList(\EbaySdk\Api\Trading\Types\AddToWatchListRequestType $request)
    {
        return $this->callOperation('AddToWatchList', $request, '\EbaySdk\Api\Trading\Types\AddToWatchListResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\AddTransactionConfirmationItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\AddTransactionConfirmationItemResponseType
     */
    public function addTransactionConfirmationItem(\EbaySdk\Api\Trading\Types\AddTransactionConfirmationItemRequestType $request)
    {
        return $this->callOperation('AddTransactionConfirmationItem', $request, '\EbaySdk\Api\Trading\Types\AddTransactionConfirmationItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\CompleteSaleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\CompleteSaleResponseType
     */
    public function completeSale(\EbaySdk\Api\Trading\Types\CompleteSaleRequestType $request)
    {
        return $this->callOperation('CompleteSale', $request, '\EbaySdk\Api\Trading\Types\CompleteSaleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ConfirmIdentityRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ConfirmIdentityResponseType
     */
    public function confirmIdentity(\EbaySdk\Api\Trading\Types\ConfirmIdentityRequestType $request)
    {
        return $this->callOperation('ConfirmIdentity', $request, '\EbaySdk\Api\Trading\Types\ConfirmIdentityResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteMyMessagesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteMyMessagesResponseType
     */
    public function deleteMyMessages(\EbaySdk\Api\Trading\Types\DeleteMyMessagesRequestType $request)
    {
        return $this->callOperation('DeleteMyMessages', $request, '\EbaySdk\Api\Trading\Types\DeleteMyMessagesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteSellingManagerInventoryFolderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteSellingManagerInventoryFolderResponseType
     */
    public function deleteSellingManagerInventoryFolder(\EbaySdk\Api\Trading\Types\DeleteSellingManagerInventoryFolderRequestType $request)
    {
        return $this->callOperation('DeleteSellingManagerInventoryFolder', $request, '\EbaySdk\Api\Trading\Types\DeleteSellingManagerInventoryFolderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteSellingManagerItemAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteSellingManagerItemAutomationRuleResponseType
     */
    public function deleteSellingManagerItemAutomationRule(\EbaySdk\Api\Trading\Types\DeleteSellingManagerItemAutomationRuleRequestType $request)
    {
        return $this->callOperation('DeleteSellingManagerItemAutomationRule', $request, '\EbaySdk\Api\Trading\Types\DeleteSellingManagerItemAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteSellingManagerProductRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteSellingManagerProductResponseType
     */
    public function deleteSellingManagerProduct(\EbaySdk\Api\Trading\Types\DeleteSellingManagerProductRequestType $request)
    {
        return $this->callOperation('DeleteSellingManagerProduct', $request, '\EbaySdk\Api\Trading\Types\DeleteSellingManagerProductResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateResponseType
     */
    public function deleteSellingManagerTemplate(\EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateRequestType $request)
    {
        return $this->callOperation('DeleteSellingManagerTemplate', $request, '\EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateAutomationRuleResponseType
     */
    public function deleteSellingManagerTemplateAutomationRule(\EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateAutomationRuleRequestType $request)
    {
        return $this->callOperation('DeleteSellingManagerTemplateAutomationRule', $request, '\EbaySdk\Api\Trading\Types\DeleteSellingManagerTemplateAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\DisableUnpaidItemAssistanceRequestType $request
     * @return \EbaySdk\Api\Trading\Types\DisableUnpaidItemAssistanceResponseType
     */
    public function disableUnpaidItemAssistance(\EbaySdk\Api\Trading\Types\DisableUnpaidItemAssistanceRequestType $request)
    {
        return $this->callOperation('DisableUnpaidItemAssistance', $request, '\EbaySdk\Api\Trading\Types\DisableUnpaidItemAssistanceResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\EndFixedPriceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\EndFixedPriceItemResponseType
     */
    public function endFixedPriceItem(\EbaySdk\Api\Trading\Types\EndFixedPriceItemRequestType $request)
    {
        return $this->callOperation('EndFixedPriceItem', $request, '\EbaySdk\Api\Trading\Types\EndFixedPriceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\EndItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\EndItemResponseType
     */
    public function endItem(\EbaySdk\Api\Trading\Types\EndItemRequestType $request)
    {
        return $this->callOperation('EndItem', $request, '\EbaySdk\Api\Trading\Types\EndItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\EndItemsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\EndItemsResponseType
     */
    public function endItems(\EbaySdk\Api\Trading\Types\EndItemsRequestType $request)
    {
        return $this->callOperation('EndItems', $request, '\EbaySdk\Api\Trading\Types\EndItemsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ExtendSiteHostedPicturesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ExtendSiteHostedPicturesResponseType
     */
    public function extendSiteHostedPictures(\EbaySdk\Api\Trading\Types\ExtendSiteHostedPicturesRequestType $request)
    {
        return $this->callOperation('ExtendSiteHostedPictures', $request, '\EbaySdk\Api\Trading\Types\ExtendSiteHostedPicturesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\FetchTokenRequestType $request
     * @return \EbaySdk\Api\Trading\Types\FetchTokenResponseType
     */
    public function fetchToken(\EbaySdk\Api\Trading\Types\FetchTokenRequestType $request)
    {
        return $this->callOperation('FetchToken', $request, '\EbaySdk\Api\Trading\Types\FetchTokenResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetAccountRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetAccountResponseType
     */
    public function getAccount(\EbaySdk\Api\Trading\Types\GetAccountRequestType $request)
    {
        return $this->callOperation('GetAccount', $request, '\EbaySdk\Api\Trading\Types\GetAccountResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetAdFormatLeadsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetAdFormatLeadsResponseType
     */
    public function getAdFormatLeads(\EbaySdk\Api\Trading\Types\GetAdFormatLeadsRequestType $request)
    {
        return $this->callOperation('GetAdFormatLeads', $request, '\EbaySdk\Api\Trading\Types\GetAdFormatLeadsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetAllBiddersRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetAllBiddersResponseType
     */
    public function getAllBidders(\EbaySdk\Api\Trading\Types\GetAllBiddersRequestType $request)
    {
        return $this->callOperation('GetAllBidders', $request, '\EbaySdk\Api\Trading\Types\GetAllBiddersResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetApiAccessRulesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetApiAccessRulesResponseType
     */
    public function getApiAccessRules(\EbaySdk\Api\Trading\Types\GetApiAccessRulesRequestType $request)
    {
        return $this->callOperation('GetApiAccessRules', $request, '\EbaySdk\Api\Trading\Types\GetApiAccessRulesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetBestOffersRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetBestOffersResponseType
     */
    public function getBestOffers(\EbaySdk\Api\Trading\Types\GetBestOffersRequestType $request)
    {
        return $this->callOperation('GetBestOffers', $request, '\EbaySdk\Api\Trading\Types\GetBestOffersResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetBidderListRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetBidderListResponseType
     */
    public function getBidderList(\EbaySdk\Api\Trading\Types\GetBidderListRequestType $request)
    {
        return $this->callOperation('GetBidderList', $request, '\EbaySdk\Api\Trading\Types\GetBidderListResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetCategoriesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetCategoriesResponseType
     */
    public function getCategories(\EbaySdk\Api\Trading\Types\GetCategoriesRequestType $request)
    {
        return $this->callOperation('GetCategories', $request, '\EbaySdk\Api\Trading\Types\GetCategoriesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetCategoryFeaturesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetCategoryFeaturesResponseType
     */
    public function getCategoryFeatures(\EbaySdk\Api\Trading\Types\GetCategoryFeaturesRequestType $request)
    {
        return $this->callOperation('GetCategoryFeatures', $request, '\EbaySdk\Api\Trading\Types\GetCategoryFeaturesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetCategoryMappingsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetCategoryMappingsResponseType
     */
    public function getCategoryMappings(\EbaySdk\Api\Trading\Types\GetCategoryMappingsRequestType $request)
    {
        return $this->callOperation('GetCategoryMappings', $request, '\EbaySdk\Api\Trading\Types\GetCategoryMappingsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetCategorySpecificsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetCategorySpecificsResponseType
     */
    public function getCategorySpecifics(\EbaySdk\Api\Trading\Types\GetCategorySpecificsRequestType $request)
    {
        return $this->callOperation('GetCategorySpecifics', $request, '\EbaySdk\Api\Trading\Types\GetCategorySpecificsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetChallengeTokenRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetChallengeTokenResponseType
     */
    public function getChallengeToken(\EbaySdk\Api\Trading\Types\GetChallengeTokenRequestType $request)
    {
        return $this->callOperation('GetChallengeToken', $request, '\EbaySdk\Api\Trading\Types\GetChallengeTokenResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetCharitiesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetCharitiesResponseType
     */
    public function getCharities(\EbaySdk\Api\Trading\Types\GetCharitiesRequestType $request)
    {
        return $this->callOperation('GetCharities', $request, '\EbaySdk\Api\Trading\Types\GetCharitiesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetClientAlertsAuthTokenRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetClientAlertsAuthTokenResponseType
     */
    public function getClientAlertsAuthToken(\EbaySdk\Api\Trading\Types\GetClientAlertsAuthTokenRequestType $request)
    {
        return $this->callOperation('GetClientAlertsAuthToken', $request, '\EbaySdk\Api\Trading\Types\GetClientAlertsAuthTokenResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetContextualKeywordsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetContextualKeywordsResponseType
     */
    public function getContextualKeywords(\EbaySdk\Api\Trading\Types\GetContextualKeywordsRequestType $request)
    {
        return $this->callOperation('GetContextualKeywords', $request, '\EbaySdk\Api\Trading\Types\GetContextualKeywordsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetDescriptionTemplatesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetDescriptionTemplatesResponseType
     */
    public function getDescriptionTemplates(\EbaySdk\Api\Trading\Types\GetDescriptionTemplatesRequestType $request)
    {
        return $this->callOperation('GetDescriptionTemplates', $request, '\EbaySdk\Api\Trading\Types\GetDescriptionTemplatesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetDisputeRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetDisputeResponseType
     */
    public function getDispute(\EbaySdk\Api\Trading\Types\GetDisputeRequestType $request)
    {
        return $this->callOperation('GetDispute', $request, '\EbaySdk\Api\Trading\Types\GetDisputeResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetFeedbackRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetFeedbackResponseType
     */
    public function getFeedback(\EbaySdk\Api\Trading\Types\GetFeedbackRequestType $request)
    {
        return $this->callOperation('GetFeedback', $request, '\EbaySdk\Api\Trading\Types\GetFeedbackResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetItemResponseType
     */
    public function getItem(\EbaySdk\Api\Trading\Types\GetItemRequestType $request)
    {
        return $this->callOperation('GetItem', $request, '\EbaySdk\Api\Trading\Types\GetItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetItemShippingRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetItemShippingResponseType
     */
    public function getItemShipping(\EbaySdk\Api\Trading\Types\GetItemShippingRequestType $request)
    {
        return $this->callOperation('GetItemShipping', $request, '\EbaySdk\Api\Trading\Types\GetItemShippingResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetItemTransactionsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetItemTransactionsResponseType
     */
    public function getItemTransactions(\EbaySdk\Api\Trading\Types\GetItemTransactionsRequestType $request)
    {
        return $this->callOperation('GetItemTransactions', $request, '\EbaySdk\Api\Trading\Types\GetItemTransactionsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetItemsAwaitingFeedbackRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetItemsAwaitingFeedbackResponseType
     */
    public function getItemsAwaitingFeedback(\EbaySdk\Api\Trading\Types\GetItemsAwaitingFeedbackRequestType $request)
    {
        return $this->callOperation('GetItemsAwaitingFeedback', $request, '\EbaySdk\Api\Trading\Types\GetItemsAwaitingFeedbackResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMemberMessagesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMemberMessagesResponseType
     */
    public function getMemberMessages(\EbaySdk\Api\Trading\Types\GetMemberMessagesRequestType $request)
    {
        return $this->callOperation('GetMemberMessages', $request, '\EbaySdk\Api\Trading\Types\GetMemberMessagesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMessagePreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMessagePreferencesResponseType
     */
    public function getMessagePreferences(\EbaySdk\Api\Trading\Types\GetMessagePreferencesRequestType $request)
    {
        return $this->callOperation('GetMessagePreferences', $request, '\EbaySdk\Api\Trading\Types\GetMessagePreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMyMessagesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMyMessagesResponseType
     */
    public function getMyMessages(\EbaySdk\Api\Trading\Types\GetMyMessagesRequestType $request)
    {
        return $this->callOperation('GetMyMessages', $request, '\EbaySdk\Api\Trading\Types\GetMyMessagesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMyeBayBuyingRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMyeBayBuyingResponseType
     */
    public function getMyeBayBuying(\EbaySdk\Api\Trading\Types\GetMyeBayBuyingRequestType $request)
    {
        return $this->callOperation('GetMyeBayBuying', $request, '\EbaySdk\Api\Trading\Types\GetMyeBayBuyingResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMyeBayRemindersRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMyeBayRemindersResponseType
     */
    public function getMyeBayReminders(\EbaySdk\Api\Trading\Types\GetMyeBayRemindersRequestType $request)
    {
        return $this->callOperation('GetMyeBayReminders', $request, '\EbaySdk\Api\Trading\Types\GetMyeBayRemindersResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetMyeBaySellingRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetMyeBaySellingResponseType
     */
    public function getMyeBaySelling(\EbaySdk\Api\Trading\Types\GetMyeBaySellingRequestType $request)
    {
        return $this->callOperation('GetMyeBaySelling', $request, '\EbaySdk\Api\Trading\Types\GetMyeBaySellingResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetNotificationPreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetNotificationPreferencesResponseType
     */
    public function getNotificationPreferences(\EbaySdk\Api\Trading\Types\GetNotificationPreferencesRequestType $request)
    {
        return $this->callOperation('GetNotificationPreferences', $request, '\EbaySdk\Api\Trading\Types\GetNotificationPreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetNotificationsUsageRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetNotificationsUsageResponseType
     */
    public function getNotificationsUsage(\EbaySdk\Api\Trading\Types\GetNotificationsUsageRequestType $request)
    {
        return $this->callOperation('GetNotificationsUsage', $request, '\EbaySdk\Api\Trading\Types\GetNotificationsUsageResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetOrderTransactionsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetOrderTransactionsResponseType
     */
    public function getOrderTransactions(\EbaySdk\Api\Trading\Types\GetOrderTransactionsRequestType $request)
    {
        return $this->callOperation('GetOrderTransactions', $request, '\EbaySdk\Api\Trading\Types\GetOrderTransactionsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetOrdersRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetOrdersResponseType
     */
    public function getOrders(\EbaySdk\Api\Trading\Types\GetOrdersRequestType $request)
    {
        return $this->callOperation('GetOrders', $request, '\EbaySdk\Api\Trading\Types\GetOrdersResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetPromotionalSaleDetailsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetPromotionalSaleDetailsResponseType
     */
    public function getPromotionalSaleDetails(\EbaySdk\Api\Trading\Types\GetPromotionalSaleDetailsRequestType $request)
    {
        return $this->callOperation('GetPromotionalSaleDetails', $request, '\EbaySdk\Api\Trading\Types\GetPromotionalSaleDetailsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellerDashboardRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellerDashboardResponseType
     */
    public function getSellerDashboard(\EbaySdk\Api\Trading\Types\GetSellerDashboardRequestType $request)
    {
        return $this->callOperation('GetSellerDashboard', $request, '\EbaySdk\Api\Trading\Types\GetSellerDashboardResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellerEventsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellerEventsResponseType
     */
    public function getSellerEvents(\EbaySdk\Api\Trading\Types\GetSellerEventsRequestType $request)
    {
        return $this->callOperation('GetSellerEvents', $request, '\EbaySdk\Api\Trading\Types\GetSellerEventsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellerListRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellerListResponseType
     */
    public function getSellerList(\EbaySdk\Api\Trading\Types\GetSellerListRequestType $request)
    {
        return $this->callOperation('GetSellerList', $request, '\EbaySdk\Api\Trading\Types\GetSellerListResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellerPaymentsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellerPaymentsResponseType
     */
    public function getSellerPayments(\EbaySdk\Api\Trading\Types\GetSellerPaymentsRequestType $request)
    {
        return $this->callOperation('GetSellerPayments', $request, '\EbaySdk\Api\Trading\Types\GetSellerPaymentsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellerTransactionsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellerTransactionsResponseType
     */
    public function getSellerTransactions(\EbaySdk\Api\Trading\Types\GetSellerTransactionsRequestType $request)
    {
        return $this->callOperation('GetSellerTransactions', $request, '\EbaySdk\Api\Trading\Types\GetSellerTransactionsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerAlertsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerAlertsResponseType
     */
    public function getSellingManagerAlerts(\EbaySdk\Api\Trading\Types\GetSellingManagerAlertsRequestType $request)
    {
        return $this->callOperation('GetSellingManagerAlerts', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerAlertsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerEmailLogRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerEmailLogResponseType
     */
    public function getSellingManagerEmailLog(\EbaySdk\Api\Trading\Types\GetSellingManagerEmailLogRequestType $request)
    {
        return $this->callOperation('GetSellingManagerEmailLog', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerEmailLogResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerInventoryRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerInventoryResponseType
     */
    public function getSellingManagerInventory(\EbaySdk\Api\Trading\Types\GetSellingManagerInventoryRequestType $request)
    {
        return $this->callOperation('GetSellingManagerInventory', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerInventoryResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerInventoryFolderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerInventoryFolderResponseType
     */
    public function getSellingManagerInventoryFolder(\EbaySdk\Api\Trading\Types\GetSellingManagerInventoryFolderRequestType $request)
    {
        return $this->callOperation('GetSellingManagerInventoryFolder', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerInventoryFolderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerItemAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerItemAutomationRuleResponseType
     */
    public function getSellingManagerItemAutomationRule(\EbaySdk\Api\Trading\Types\GetSellingManagerItemAutomationRuleRequestType $request)
    {
        return $this->callOperation('GetSellingManagerItemAutomationRule', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerItemAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerSaleRecordRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerSaleRecordResponseType
     */
    public function getSellingManagerSaleRecord(\EbaySdk\Api\Trading\Types\GetSellingManagerSaleRecordRequestType $request)
    {
        return $this->callOperation('GetSellingManagerSaleRecord', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerSaleRecordResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerSoldListingsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerSoldListingsResponseType
     */
    public function getSellingManagerSoldListings(\EbaySdk\Api\Trading\Types\GetSellingManagerSoldListingsRequestType $request)
    {
        return $this->callOperation('GetSellingManagerSoldListings', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerSoldListingsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerTemplateAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerTemplateAutomationRuleResponseType
     */
    public function getSellingManagerTemplateAutomationRule(\EbaySdk\Api\Trading\Types\GetSellingManagerTemplateAutomationRuleRequestType $request)
    {
        return $this->callOperation('GetSellingManagerTemplateAutomationRule', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerTemplateAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSellingManagerTemplatesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSellingManagerTemplatesResponseType
     */
    public function getSellingManagerTemplates(\EbaySdk\Api\Trading\Types\GetSellingManagerTemplatesRequestType $request)
    {
        return $this->callOperation('GetSellingManagerTemplates', $request, '\EbaySdk\Api\Trading\Types\GetSellingManagerTemplatesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSessionIDRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSessionIDResponseType
     */
    public function getSessionID(\EbaySdk\Api\Trading\Types\GetSessionIDRequestType $request)
    {
        return $this->callOperation('GetSessionID', $request, '\EbaySdk\Api\Trading\Types\GetSessionIDResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetShippingDiscountProfilesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetShippingDiscountProfilesResponseType
     */
    public function getShippingDiscountProfiles(\EbaySdk\Api\Trading\Types\GetShippingDiscountProfilesRequestType $request)
    {
        return $this->callOperation('GetShippingDiscountProfiles', $request, '\EbaySdk\Api\Trading\Types\GetShippingDiscountProfilesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetStoreRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetStoreResponseType
     */
    public function getStore(\EbaySdk\Api\Trading\Types\GetStoreRequestType $request)
    {
        return $this->callOperation('GetStore', $request, '\EbaySdk\Api\Trading\Types\GetStoreResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetStoreCategoryUpdateStatusRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetStoreCategoryUpdateStatusResponseType
     */
    public function getStoreCategoryUpdateStatus(\EbaySdk\Api\Trading\Types\GetStoreCategoryUpdateStatusRequestType $request)
    {
        return $this->callOperation('GetStoreCategoryUpdateStatus', $request, '\EbaySdk\Api\Trading\Types\GetStoreCategoryUpdateStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetStoreCustomPageRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetStoreCustomPageResponseType
     */
    public function getStoreCustomPage(\EbaySdk\Api\Trading\Types\GetStoreCustomPageRequestType $request)
    {
        return $this->callOperation('GetStoreCustomPage', $request, '\EbaySdk\Api\Trading\Types\GetStoreCustomPageResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetStoreOptionsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetStoreOptionsResponseType
     */
    public function getStoreOptions(\EbaySdk\Api\Trading\Types\GetStoreOptionsRequestType $request)
    {
        return $this->callOperation('GetStoreOptions', $request, '\EbaySdk\Api\Trading\Types\GetStoreOptionsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetStorePreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetStorePreferencesResponseType
     */
    public function getStorePreferences(\EbaySdk\Api\Trading\Types\GetStorePreferencesRequestType $request)
    {
        return $this->callOperation('GetStorePreferences', $request, '\EbaySdk\Api\Trading\Types\GetStorePreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetSuggestedCategoriesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetSuggestedCategoriesResponseType
     */
    public function getSuggestedCategories(\EbaySdk\Api\Trading\Types\GetSuggestedCategoriesRequestType $request)
    {
        return $this->callOperation('GetSuggestedCategories', $request, '\EbaySdk\Api\Trading\Types\GetSuggestedCategoriesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetTaxTableRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetTaxTableResponseType
     */
    public function getTaxTable(\EbaySdk\Api\Trading\Types\GetTaxTableRequestType $request)
    {
        return $this->callOperation('GetTaxTable', $request, '\EbaySdk\Api\Trading\Types\GetTaxTableResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetTokenStatusRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetTokenStatusResponseType
     */
    public function getTokenStatus(\EbaySdk\Api\Trading\Types\GetTokenStatusRequestType $request)
    {
        return $this->callOperation('GetTokenStatus', $request, '\EbaySdk\Api\Trading\Types\GetTokenStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetUserRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetUserResponseType
     */
    public function getUser(\EbaySdk\Api\Trading\Types\GetUserRequestType $request)
    {
        return $this->callOperation('GetUser', $request, '\EbaySdk\Api\Trading\Types\GetUserResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetUserContactDetailsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetUserContactDetailsResponseType
     */
    public function getUserContactDetails(\EbaySdk\Api\Trading\Types\GetUserContactDetailsRequestType $request)
    {
        return $this->callOperation('GetUserContactDetails', $request, '\EbaySdk\Api\Trading\Types\GetUserContactDetailsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetUserDisputesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetUserDisputesResponseType
     */
    public function getUserDisputes(\EbaySdk\Api\Trading\Types\GetUserDisputesRequestType $request)
    {
        return $this->callOperation('GetUserDisputes', $request, '\EbaySdk\Api\Trading\Types\GetUserDisputesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetUserPreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetUserPreferencesResponseType
     */
    public function getUserPreferences(\EbaySdk\Api\Trading\Types\GetUserPreferencesRequestType $request)
    {
        return $this->callOperation('GetUserPreferences', $request, '\EbaySdk\Api\Trading\Types\GetUserPreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetVeROReasonCodeDetailsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetVeROReasonCodeDetailsResponseType
     */
    public function getVeROReasonCodeDetails(\EbaySdk\Api\Trading\Types\GetVeROReasonCodeDetailsRequestType $request)
    {
        return $this->callOperation('GetVeROReasonCodeDetails', $request, '\EbaySdk\Api\Trading\Types\GetVeROReasonCodeDetailsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GetVeROReportStatusRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GetVeROReportStatusResponseType
     */
    public function getVeROReportStatus(\EbaySdk\Api\Trading\Types\GetVeROReportStatusRequestType $request)
    {
        return $this->callOperation('GetVeROReportStatus', $request, '\EbaySdk\Api\Trading\Types\GetVeROReportStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GeteBayDetailsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GeteBayDetailsResponseType
     */
    public function geteBayDetails(\EbaySdk\Api\Trading\Types\GeteBayDetailsRequestType $request)
    {
        return $this->callOperation('GeteBayDetails', $request, '\EbaySdk\Api\Trading\Types\GeteBayDetailsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\GeteBayOfficialTimeRequestType $request
     * @return \EbaySdk\Api\Trading\Types\GeteBayOfficialTimeResponseType
     */
    public function geteBayOfficialTime(\EbaySdk\Api\Trading\Types\GeteBayOfficialTimeRequestType $request)
    {
        return $this->callOperation('GeteBayOfficialTime', $request, '\EbaySdk\Api\Trading\Types\GeteBayOfficialTimeResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\IssueRefundRequestType $request
     * @return \EbaySdk\Api\Trading\Types\IssueRefundResponseType
     */
    public function issueRefund(\EbaySdk\Api\Trading\Types\IssueRefundRequestType $request)
    {
        return $this->callOperation('IssueRefund', $request, '\EbaySdk\Api\Trading\Types\IssueRefundResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\LeaveFeedbackRequestType $request
     * @return \EbaySdk\Api\Trading\Types\LeaveFeedbackResponseType
     */
    public function leaveFeedback(\EbaySdk\Api\Trading\Types\LeaveFeedbackRequestType $request)
    {
        return $this->callOperation('LeaveFeedback', $request, '\EbaySdk\Api\Trading\Types\LeaveFeedbackResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\MoveSellingManagerInventoryFolderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\MoveSellingManagerInventoryFolderResponseType
     */
    public function moveSellingManagerInventoryFolder(\EbaySdk\Api\Trading\Types\MoveSellingManagerInventoryFolderRequestType $request)
    {
        return $this->callOperation('MoveSellingManagerInventoryFolder', $request, '\EbaySdk\Api\Trading\Types\MoveSellingManagerInventoryFolderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\PlaceOfferRequestType $request
     * @return \EbaySdk\Api\Trading\Types\PlaceOfferResponseType
     */
    public function placeOffer(\EbaySdk\Api\Trading\Types\PlaceOfferRequestType $request)
    {
        return $this->callOperation('PlaceOffer', $request, '\EbaySdk\Api\Trading\Types\PlaceOfferResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RelistFixedPriceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RelistFixedPriceItemResponseType
     */
    public function relistFixedPriceItem(\EbaySdk\Api\Trading\Types\RelistFixedPriceItemRequestType $request)
    {
        return $this->callOperation('RelistFixedPriceItem', $request, '\EbaySdk\Api\Trading\Types\RelistFixedPriceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RelistItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RelistItemResponseType
     */
    public function relistItem(\EbaySdk\Api\Trading\Types\RelistItemRequestType $request)
    {
        return $this->callOperation('RelistItem', $request, '\EbaySdk\Api\Trading\Types\RelistItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RemoveFromWatchListRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RemoveFromWatchListResponseType
     */
    public function removeFromWatchList(\EbaySdk\Api\Trading\Types\RemoveFromWatchListRequestType $request)
    {
        return $this->callOperation('RemoveFromWatchList', $request, '\EbaySdk\Api\Trading\Types\RemoveFromWatchListResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RespondToBestOfferRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RespondToBestOfferResponseType
     */
    public function respondToBestOffer(\EbaySdk\Api\Trading\Types\RespondToBestOfferRequestType $request)
    {
        return $this->callOperation('RespondToBestOffer', $request, '\EbaySdk\Api\Trading\Types\RespondToBestOfferResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RespondToFeedbackRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RespondToFeedbackResponseType
     */
    public function respondToFeedback(\EbaySdk\Api\Trading\Types\RespondToFeedbackRequestType $request)
    {
        return $this->callOperation('RespondToFeedback', $request, '\EbaySdk\Api\Trading\Types\RespondToFeedbackResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseCheckoutStatusRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseCheckoutStatusResponseType
     */
    public function reviseCheckoutStatus(\EbaySdk\Api\Trading\Types\ReviseCheckoutStatusRequestType $request)
    {
        return $this->callOperation('ReviseCheckoutStatus', $request, '\EbaySdk\Api\Trading\Types\ReviseCheckoutStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseFixedPriceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseFixedPriceItemResponseType
     */
    public function reviseFixedPriceItem(\EbaySdk\Api\Trading\Types\ReviseFixedPriceItemRequestType $request)
    {
        return $this->callOperation('ReviseFixedPriceItem', $request, '\EbaySdk\Api\Trading\Types\ReviseFixedPriceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseInventoryStatusRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseInventoryStatusResponseType
     */
    public function reviseInventoryStatus(\EbaySdk\Api\Trading\Types\ReviseInventoryStatusRequestType $request)
    {
        return $this->callOperation('ReviseInventoryStatus', $request, '\EbaySdk\Api\Trading\Types\ReviseInventoryStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseItemResponseType
     */
    public function reviseItem(\EbaySdk\Api\Trading\Types\ReviseItemRequestType $request)
    {
        return $this->callOperation('ReviseItem', $request, '\EbaySdk\Api\Trading\Types\ReviseItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseMyMessagesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseMyMessagesResponseType
     */
    public function reviseMyMessages(\EbaySdk\Api\Trading\Types\ReviseMyMessagesRequestType $request)
    {
        return $this->callOperation('ReviseMyMessages', $request, '\EbaySdk\Api\Trading\Types\ReviseMyMessagesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseMyMessagesFoldersRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseMyMessagesFoldersResponseType
     */
    public function reviseMyMessagesFolders(\EbaySdk\Api\Trading\Types\ReviseMyMessagesFoldersRequestType $request)
    {
        return $this->callOperation('ReviseMyMessagesFolders', $request, '\EbaySdk\Api\Trading\Types\ReviseMyMessagesFoldersResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseSellingManagerInventoryFolderRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseSellingManagerInventoryFolderResponseType
     */
    public function reviseSellingManagerInventoryFolder(\EbaySdk\Api\Trading\Types\ReviseSellingManagerInventoryFolderRequestType $request)
    {
        return $this->callOperation('ReviseSellingManagerInventoryFolder', $request, '\EbaySdk\Api\Trading\Types\ReviseSellingManagerInventoryFolderResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseSellingManagerProductRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseSellingManagerProductResponseType
     */
    public function reviseSellingManagerProduct(\EbaySdk\Api\Trading\Types\ReviseSellingManagerProductRequestType $request)
    {
        return $this->callOperation('ReviseSellingManagerProduct', $request, '\EbaySdk\Api\Trading\Types\ReviseSellingManagerProductResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseSellingManagerSaleRecordRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseSellingManagerSaleRecordResponseType
     */
    public function reviseSellingManagerSaleRecord(\EbaySdk\Api\Trading\Types\ReviseSellingManagerSaleRecordRequestType $request)
    {
        return $this->callOperation('ReviseSellingManagerSaleRecord', $request, '\EbaySdk\Api\Trading\Types\ReviseSellingManagerSaleRecordResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ReviseSellingManagerTemplateRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ReviseSellingManagerTemplateResponseType
     */
    public function reviseSellingManagerTemplate(\EbaySdk\Api\Trading\Types\ReviseSellingManagerTemplateRequestType $request)
    {
        return $this->callOperation('ReviseSellingManagerTemplate', $request, '\EbaySdk\Api\Trading\Types\ReviseSellingManagerTemplateResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\RevokeTokenRequestType $request
     * @return \EbaySdk\Api\Trading\Types\RevokeTokenResponseType
     */
    public function revokeToken(\EbaySdk\Api\Trading\Types\RevokeTokenRequestType $request)
    {
        return $this->callOperation('RevokeToken', $request, '\EbaySdk\Api\Trading\Types\RevokeTokenResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SaveItemToSellingManagerTemplateRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SaveItemToSellingManagerTemplateResponseType
     */
    public function saveItemToSellingManagerTemplate(\EbaySdk\Api\Trading\Types\SaveItemToSellingManagerTemplateRequestType $request)
    {
        return $this->callOperation('SaveItemToSellingManagerTemplate', $request, '\EbaySdk\Api\Trading\Types\SaveItemToSellingManagerTemplateResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SellerReverseDisputeRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SellerReverseDisputeResponseType
     */
    public function sellerReverseDispute(\EbaySdk\Api\Trading\Types\SellerReverseDisputeRequestType $request)
    {
        return $this->callOperation('SellerReverseDispute', $request, '\EbaySdk\Api\Trading\Types\SellerReverseDisputeResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SendInvoiceRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SendInvoiceResponseType
     */
    public function sendInvoice(\EbaySdk\Api\Trading\Types\SendInvoiceRequestType $request)
    {
        return $this->callOperation('SendInvoice', $request, '\EbaySdk\Api\Trading\Types\SendInvoiceResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetMessagePreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetMessagePreferencesResponseType
     */
    public function setMessagePreferences(\EbaySdk\Api\Trading\Types\SetMessagePreferencesRequestType $request)
    {
        return $this->callOperation('SetMessagePreferences', $request, '\EbaySdk\Api\Trading\Types\SetMessagePreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetNotificationPreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetNotificationPreferencesResponseType
     */
    public function setNotificationPreferences(\EbaySdk\Api\Trading\Types\SetNotificationPreferencesRequestType $request)
    {
        return $this->callOperation('SetNotificationPreferences', $request, '\EbaySdk\Api\Trading\Types\SetNotificationPreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetPromotionalSaleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetPromotionalSaleResponseType
     */
    public function setPromotionalSale(\EbaySdk\Api\Trading\Types\SetPromotionalSaleRequestType $request)
    {
        return $this->callOperation('SetPromotionalSale', $request, '\EbaySdk\Api\Trading\Types\SetPromotionalSaleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetPromotionalSaleListingsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetPromotionalSaleListingsResponseType
     */
    public function setPromotionalSaleListings(\EbaySdk\Api\Trading\Types\SetPromotionalSaleListingsRequestType $request)
    {
        return $this->callOperation('SetPromotionalSaleListings', $request, '\EbaySdk\Api\Trading\Types\SetPromotionalSaleListingsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetSellingManagerFeedbackOptionsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetSellingManagerFeedbackOptionsResponseType
     */
    public function setSellingManagerFeedbackOptions(\EbaySdk\Api\Trading\Types\SetSellingManagerFeedbackOptionsRequestType $request)
    {
        return $this->callOperation('SetSellingManagerFeedbackOptions', $request, '\EbaySdk\Api\Trading\Types\SetSellingManagerFeedbackOptionsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetSellingManagerItemAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetSellingManagerItemAutomationRuleResponseType
     */
    public function setSellingManagerItemAutomationRule(\EbaySdk\Api\Trading\Types\SetSellingManagerItemAutomationRuleRequestType $request)
    {
        return $this->callOperation('SetSellingManagerItemAutomationRule', $request, '\EbaySdk\Api\Trading\Types\SetSellingManagerItemAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetSellingManagerTemplateAutomationRuleRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetSellingManagerTemplateAutomationRuleResponseType
     */
    public function setSellingManagerTemplateAutomationRule(\EbaySdk\Api\Trading\Types\SetSellingManagerTemplateAutomationRuleRequestType $request)
    {
        return $this->callOperation('SetSellingManagerTemplateAutomationRule', $request, '\EbaySdk\Api\Trading\Types\SetSellingManagerTemplateAutomationRuleResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetShippingDiscountProfilesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetShippingDiscountProfilesResponseType
     */
    public function setShippingDiscountProfiles(\EbaySdk\Api\Trading\Types\SetShippingDiscountProfilesRequestType $request)
    {
        return $this->callOperation('SetShippingDiscountProfiles', $request, '\EbaySdk\Api\Trading\Types\SetShippingDiscountProfilesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetStoreRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetStoreResponseType
     */
    public function setStore(\EbaySdk\Api\Trading\Types\SetStoreRequestType $request)
    {
        return $this->callOperation('SetStore', $request, '\EbaySdk\Api\Trading\Types\SetStoreResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetStoreCategoriesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetStoreCategoriesResponseType
     */
    public function setStoreCategories(\EbaySdk\Api\Trading\Types\SetStoreCategoriesRequestType $request)
    {
        return $this->callOperation('SetStoreCategories', $request, '\EbaySdk\Api\Trading\Types\SetStoreCategoriesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetStoreCustomPageRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetStoreCustomPageResponseType
     */
    public function setStoreCustomPage(\EbaySdk\Api\Trading\Types\SetStoreCustomPageRequestType $request)
    {
        return $this->callOperation('SetStoreCustomPage', $request, '\EbaySdk\Api\Trading\Types\SetStoreCustomPageResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetStorePreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetStorePreferencesResponseType
     */
    public function setStorePreferences(\EbaySdk\Api\Trading\Types\SetStorePreferencesRequestType $request)
    {
        return $this->callOperation('SetStorePreferences', $request, '\EbaySdk\Api\Trading\Types\SetStorePreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetTaxTableRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetTaxTableResponseType
     */
    public function setTaxTable(\EbaySdk\Api\Trading\Types\SetTaxTableRequestType $request)
    {
        return $this->callOperation('SetTaxTable', $request, '\EbaySdk\Api\Trading\Types\SetTaxTableResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetUserNotesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetUserNotesResponseType
     */
    public function setUserNotes(\EbaySdk\Api\Trading\Types\SetUserNotesRequestType $request)
    {
        return $this->callOperation('SetUserNotes', $request, '\EbaySdk\Api\Trading\Types\SetUserNotesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\SetUserPreferencesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\SetUserPreferencesResponseType
     */
    public function setUserPreferences(\EbaySdk\Api\Trading\Types\SetUserPreferencesRequestType $request)
    {
        return $this->callOperation('SetUserPreferences', $request, '\EbaySdk\Api\Trading\Types\SetUserPreferencesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\UploadSiteHostedPicturesRequestType $request
     * @return \EbaySdk\Api\Trading\Types\UploadSiteHostedPicturesResponseType
     */
    public function uploadSiteHostedPictures(\EbaySdk\Api\Trading\Types\UploadSiteHostedPicturesRequestType $request)
    {
        return $this->callOperation('UploadSiteHostedPictures', $request, '\EbaySdk\Api\Trading\Types\UploadSiteHostedPicturesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ValidateChallengeInputRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ValidateChallengeInputResponseType
     */
    public function validateChallengeInput(\EbaySdk\Api\Trading\Types\ValidateChallengeInputRequestType $request)
    {
        return $this->callOperation('ValidateChallengeInput', $request, '\EbaySdk\Api\Trading\Types\ValidateChallengeInputResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\ValidateTestUserRegistrationRequestType $request
     * @return \EbaySdk\Api\Trading\Types\ValidateTestUserRegistrationResponseType
     */
    public function validateTestUserRegistration(\EbaySdk\Api\Trading\Types\ValidateTestUserRegistrationRequestType $request)
    {
        return $this->callOperation('ValidateTestUserRegistration', $request, '\EbaySdk\Api\Trading\Types\ValidateTestUserRegistrationResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\VeROReportItemsRequestType $request
     * @return \EbaySdk\Api\Trading\Types\VeROReportItemsResponseType
     */
    public function veROReportItems(\EbaySdk\Api\Trading\Types\VeROReportItemsRequestType $request)
    {
        return $this->callOperation('VeROReportItems', $request, '\EbaySdk\Api\Trading\Types\VeROReportItemsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\VerifyAddFixedPriceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\VerifyAddFixedPriceItemResponseType
     */
    public function verifyAddFixedPriceItem(\EbaySdk\Api\Trading\Types\VerifyAddFixedPriceItemRequestType $request)
    {
        return $this->callOperation('VerifyAddFixedPriceItem', $request, '\EbaySdk\Api\Trading\Types\VerifyAddFixedPriceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\VerifyAddItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\VerifyAddItemResponseType
     */
    public function verifyAddItem(\EbaySdk\Api\Trading\Types\VerifyAddItemRequestType $request)
    {
        return $this->callOperation('VerifyAddItem', $request, '\EbaySdk\Api\Trading\Types\VerifyAddItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\VerifyAddSecondChanceItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\VerifyAddSecondChanceItemResponseType
     */
    public function verifyAddSecondChanceItem(\EbaySdk\Api\Trading\Types\VerifyAddSecondChanceItemRequestType $request)
    {
        return $this->callOperation('VerifyAddSecondChanceItem', $request, '\EbaySdk\Api\Trading\Types\VerifyAddSecondChanceItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Trading\Types\VerifyRelistItemRequestType $request
     * @return \EbaySdk\Api\Trading\Types\VerifyRelistItemResponseType
     */
    public function verifyRelistItem(\EbaySdk\Api\Trading\Types\VerifyRelistItemRequestType $request)
    {
        return $this->callOperation('VerifyRelistItem', $request, '\EbaySdk\Api\Trading\Types\VerifyRelistItemResponseType');
    }
}
