<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Browse\Services;

class BrowseService extends \EbaySdk\Api\Browse\Services\BrowseBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'GetItem' => [
            'method' => 'GET',
            'resource' => 'item/{item_id}',
            'responseClass' => '\EbaySdk\Api\Browse\Types\GetItemRestResponse',
            'params' => [
                'item_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetItemByLegacyId' => [
            'method' => 'GET',
            'resource' => 'item/get_item_by_legacy_id',
            'responseClass' => '\EbaySdk\Api\Browse\Types\GetItemByLegacyIdRestResponse',
            'params' => [
                'legacy_item_id' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'legacy_variation_id' => [
                    'valid' => ['string']
                ],
                'legacy_variation_sku' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'GetItemsByItemGroup' => [
            'method' => 'GET',
            'resource' => 'item/get_items_by_item_group',
            'responseClass' => '\EbaySdk\Api\Browse\Types\GetItemsByItemGroupRestResponse',
            'params' => [
                'item_group_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SearchForItems' => [
            'method' => 'GET',
            'resource' => 'item_summary/search',
            'responseClass' => '\EbaySdk\Api\Browse\Types\SearchForItemsRestResponse',
            'params' => [
                'aspect_filter' => [
                    'valid' => ['string']
                ],
                'category_ids' => [
                    'valid' => ['string']
                ],
                'epid' => [
                    'valid' => ['string']
                ],
                'fieldgroups' => [
                    'valid' => ['string']
                ],
                'filter' => [
                    'valid' => ['string']
                ],
                'gtin' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'q' => [
                    'valid' => ['string']
                ],
                'sort' => [
                    'valid' => ['string']
                ]
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \EbaySdk\Api\Browse\Types\GetItemRestRequest $request
     * @return \EbaySdk\Api\Browse\Types\GetItemRestResponse
     */
    public function getItem(\EbaySdk\Api\Browse\Types\GetItemRestRequest $request)
    {
        return $this->callOperation('GetItem', $request);
    }

    /**
     * @param \EbaySdk\Api\Browse\Types\GetItemByLegacyIdRestRequest $request
     * @return \EbaySdk\Api\Browse\Types\GetItemByLegacyIdRestResponse
     */
    public function getItemByLegacyId(\EbaySdk\Api\Browse\Types\GetItemByLegacyIdRestRequest $request)
    {
        return $this->callOperation('GetItemByLegacyId', $request);
    }

    /**
     * @param \EbaySdk\Api\Browse\Types\GetItemsByItemGroupRestRequest $request
     * @return \EbaySdk\Api\Browse\Types\GetItemsByItemGroupRestResponse
     */
    public function getItemsByItemGroup(\EbaySdk\Api\Browse\Types\GetItemsByItemGroupRestRequest $request)
    {
        return $this->callOperation('GetItemsByItemGroup', $request);
    }

    /**
     * @param \EbaySdk\Api\Browse\Types\SearchForItemsRestRequest $request
     * @return \EbaySdk\Api\Browse\Types\SearchForItemsRestResponse
     */
    public function searchForItems(\EbaySdk\Api\Browse\Types\SearchForItemsRestRequest $request)
    {
        return $this->callOperation('SearchForItems', $request);
    }
}
