<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Finding\Types;

/**
 *
 * @property \EbaySdk\Finding\Types\Amount $originalRetailPrice
 * @property \EbaySdk\Finding\Enums\MapExposureEnum $minimumAdvertisedPriceExposure
 * @property \EbaySdk\Finding\Enums\PriceTreatmentEnum $pricingTreatment
 * @property boolean $soldOnEbay
 * @property boolean $soldOffEbay
 */
class DiscountPriceInfo extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'originalRetailPrice' => [
            'type' => 'EbaySdk\Finding\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'originalRetailPrice'
        ],
        'minimumAdvertisedPriceExposure' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minimumAdvertisedPriceExposure'
        ],
        'pricingTreatment' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'pricingTreatment'
        ],
        'soldOnEbay' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'soldOnEbay'
        ],
        'soldOffEbay' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'soldOffEbay'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/search/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
