<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Marketing\Types;

/**
 *
 * @property string[] $brands
 * @property string[] $categoryIds
 * @property \EbaySdk\Api\Marketing\Enums\CategoryScopeEnum $categoryScope
 * @property string[] $listingConditionIds
 * @property \EbaySdk\Api\Marketing\Types\Amount $maxPrice
 * @property \EbaySdk\Api\Marketing\Types\Amount $minPrice
 */
class SelectionRule extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'brands' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'brands'
        ],
        'categoryIds' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'categoryIds'
        ],
        'categoryScope' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'categoryScope'
        ],
        'listingConditionIds' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'listingConditionIds'
        ],
        'maxPrice' => [
            'type' => 'EbaySdk\Api\Marketing\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'maxPrice'
        ],
        'minPrice' => [
            'type' => 'EbaySdk\Api\Marketing\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minPrice'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[\Plenty\Modules\Market\Ebay\Api\Types\BaseType::class], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
