<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Merchandising\Types;

/**
 *
 * @property string $itemId
 * @property string[] $categoryId
 * @property string[] $categoryIdExclude
 * @property string $listingType
 * @property \DateTime $endTimeTo
 * @property \DateTime $endTimeFrom
 * @property \EbaySdk\Merchandising\Types\Amount $maxPrice
 * @property \EbaySdk\Merchandising\Types\ItemFilter[] $itemFilter
 */
class GetSimilarItemsRequest extends \EbaySdk\Api\Merchandising\Types\BaseMerchandisingServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'itemId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'itemId'
        ],
        'categoryId' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'categoryId'
        ],
        'categoryIdExclude' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'categoryIdExclude'
        ],
        'listingType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'listingType'
        ],
        'endTimeTo' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'endTimeTo'
        ],
        'endTimeFrom' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'endTimeFrom'
        ],
        'maxPrice' => [
            'type' => 'EbaySdk\Merchandising\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'maxPrice'
        ],
        'itemFilter' => [
            'type' => 'EbaySdk\Merchandising\Types\ItemFilter',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'itemFilter'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'getSimilarItemsRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
