<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Merchandising\Types;

/**
 *
 * @property string $itemId
 * @property string $title
 * @property string $viewItemURL
 * @property \EbaySdk\Merchandising\Types\Amount $currentPrice
 * @property \EbaySdk\Merchandising\Types\Amount $originalPrice
 * @property string $globalId
 * @property string $timeLeft
 * @property string $primaryCategoryId
 * @property string $primaryCategoryName
 * @property string $subtitle
 * @property integer $bidCount
 * @property \EbaySdk\Merchandising\Types\Amount $buyItNowPrice
 * @property string $country
 * @property string $imageURL
 * @property \EbaySdk\Merchandising\Types\Amount $shippingCost
 * @property string $shippingType
 * @property integer $watchCount
 * @property \EbaySdk\Merchandising\Types\DiscountPriceInfo $discountPriceInfo
 */
class Item extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'itemId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'itemId'
        ],
        'title' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'title'
        ],
        'viewItemURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'viewItemURL'
        ],
        'currentPrice' => [
            'type' => 'EbaySdk\Merchandising\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'currentPrice'
        ],
        'originalPrice' => [
            'type' => 'EbaySdk\Merchandising\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'originalPrice'
        ],
        'globalId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'globalId'
        ],
        'timeLeft' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'timeLeft'
        ],
        'primaryCategoryId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'primaryCategoryId'
        ],
        'primaryCategoryName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'primaryCategoryName'
        ],
        'subtitle' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'subtitle'
        ],
        'bidCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'bidCount'
        ],
        'buyItNowPrice' => [
            'type' => 'EbaySdk\Merchandising\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'buyItNowPrice'
        ],
        'country' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'country'
        ],
        'imageURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'imageURL'
        ],
        'shippingCost' => [
            'type' => 'EbaySdk\Merchandising\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingCost'
        ],
        'shippingType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingType'
        ],
        'watchCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'watchCount'
        ],
        'discountPriceInfo' => [
            'type' => 'EbaySdk\Merchandising\Types\DiscountPriceInfo',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'discountPriceInfo'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
