<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Trading\Types;

/**
 *
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $ScheduledList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $ActiveList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $SoldList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $UnsoldList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $BidList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $DeletedFromSoldList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $DeletedFromUnsoldList
 * @property \EbaySdk\Api\Trading\Types\ItemListCustomizationType $SellingSummary
 * @property boolean $HideVariations
 */
class GetMyeBaySellingRequestType extends \EbaySdk\Api\Trading\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ScheduledList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ScheduledList'
        ],
        'ActiveList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ActiveList'
        ],
        'SoldList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SoldList'
        ],
        'UnsoldList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UnsoldList'
        ],
        'BidList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BidList'
        ],
        'DeletedFromSoldList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DeletedFromSoldList'
        ],
        'DeletedFromUnsoldList' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DeletedFromUnsoldList'
        ],
        'SellingSummary' => [
            'type' => 'EbaySdk\Api\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellingSummary'
        ],
        'HideVariations' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HideVariations'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[\EbaySdk\Api\Trading\Types\AbstractRequestType::class], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'GetMyeBaySellingRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
