<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Trading\Types;

/**
 *
 * @property \EbaySdk\Trading\Types\StoreThemeArrayType $BasicThemeArray
 * @property \EbaySdk\Trading\Types\StoreThemeArrayType $AdvancedThemeArray
 * @property \EbaySdk\Trading\Types\StoreLogoArrayType $LogoArray
 * @property \EbaySdk\Trading\Types\StoreSubscriptionArrayType $SubscriptionArray
 * @property integer $MaxCategories
 * @property integer $MaxCategoryLevels
 */
class GetStoreOptionsResponseType extends \EbaySdk\Api\Trading\Types\AbstractResponseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'BasicThemeArray' => [
            'type' => 'EbaySdk\Trading\Types\StoreThemeArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BasicThemeArray'
        ],
        'AdvancedThemeArray' => [
            'type' => 'EbaySdk\Trading\Types\StoreThemeArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdvancedThemeArray'
        ],
        'LogoArray' => [
            'type' => 'EbaySdk\Trading\Types\StoreLogoArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LogoArray'
        ],
        'SubscriptionArray' => [
            'type' => 'EbaySdk\Trading\Types\StoreSubscriptionArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SubscriptionArray'
        ],
        'MaxCategories' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxCategories'
        ],
        'MaxCategoryLevels' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxCategoryLevels'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
