<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Trading\Types;

/**
 *
 * @property \EbaySdk\Trading\Enums\CurrencyCodeType $CurrencyID
 * @property \EbaySdk\Trading\Types\FlatShippingDiscountType $FlatShippingDiscount
 * @property \EbaySdk\Trading\Types\CalculatedShippingDiscountType $CalculatedShippingDiscount
 * @property boolean $PromotionalShippingDiscount
 * @property \EbaySdk\Trading\Types\CalculatedHandlingDiscountType $CalculatedHandlingDiscount
 * @property \EbaySdk\Trading\Types\PromotionalShippingDiscountDetailsType $PromotionalShippingDiscountDetails
 * @property \EbaySdk\Trading\Types\ShippingInsuranceType $ShippingInsurance
 * @property \EbaySdk\Trading\Types\ShippingInsuranceType $InternationalShippingInsurance
 * @property \EbaySdk\Trading\Enums\CombinedPaymentPeriodCodeType $CombinedDuration
 */
class GetShippingDiscountProfilesResponseType extends \EbaySdk\Api\Trading\Types\AbstractResponseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'CurrencyID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CurrencyID'
        ],
        'FlatShippingDiscount' => [
            'type' => 'EbaySdk\Trading\Types\FlatShippingDiscountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FlatShippingDiscount'
        ],
        'CalculatedShippingDiscount' => [
            'type' => 'EbaySdk\Trading\Types\CalculatedShippingDiscountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CalculatedShippingDiscount'
        ],
        'PromotionalShippingDiscount' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PromotionalShippingDiscount'
        ],
        'CalculatedHandlingDiscount' => [
            'type' => 'EbaySdk\Trading\Types\CalculatedHandlingDiscountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CalculatedHandlingDiscount'
        ],
        'PromotionalShippingDiscountDetails' => [
            'type' => 'EbaySdk\Trading\Types\PromotionalShippingDiscountDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PromotionalShippingDiscountDetails'
        ],
        'ShippingInsurance' => [
            'type' => 'EbaySdk\Trading\Types\ShippingInsuranceType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingInsurance'
        ],
        'InternationalShippingInsurance' => [
            'type' => 'EbaySdk\Trading\Types\ShippingInsuranceType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalShippingInsurance'
        ],
        'CombinedDuration' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CombinedDuration'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
