<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Finding\Enums;

/**
 *
 */
class MapExposureEnum
{
    const C_DURING_CHECKOUT = 'DuringCheckout';
    const C_PRE_CHECKOUT = 'PreCheckout';
}
