<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Shopping\Services;

class ShoppingService extends \EbaySdk\Api\Shopping\Services\ShoppingBaseService
{
    const API_VERSION = '983';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\FindHalfProductsRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\FindHalfProductsResponseType
     */
    public function findHalfProducts(\EbaySdk\Api\Shopping\Types\FindHalfProductsRequestType $request)
    {
        return $this->callOperation('FindHalfProducts', $request, '\EbaySdk\Api\Shopping\Types\FindHalfProductsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\FindProductsRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\FindProductsResponseType
     */
    public function findProducts(\EbaySdk\Api\Shopping\Types\FindProductsRequestType $request)
    {
        return $this->callOperation('FindProducts', $request, '\EbaySdk\Api\Shopping\Types\FindProductsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\FindReviewsAndGuidesRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\FindReviewsAndGuidesResponseType
     */
    public function findReviewsAndGuides(\EbaySdk\Api\Shopping\Types\FindReviewsAndGuidesRequestType $request)
    {
        return $this->callOperation('FindReviewsAndGuides', $request, '\EbaySdk\Api\Shopping\Types\FindReviewsAndGuidesResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetCategoryInfoRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetCategoryInfoResponseType
     */
    public function getCategoryInfo(\EbaySdk\Api\Shopping\Types\GetCategoryInfoRequestType $request)
    {
        return $this->callOperation('GetCategoryInfo', $request, '\EbaySdk\Api\Shopping\Types\GetCategoryInfoResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetItemStatusRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetItemStatusResponseType
     */
    public function getItemStatus(\EbaySdk\Api\Shopping\Types\GetItemStatusRequestType $request)
    {
        return $this->callOperation('GetItemStatus', $request, '\EbaySdk\Api\Shopping\Types\GetItemStatusResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetMultipleItemsRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetMultipleItemsResponseType
     */
    public function getMultipleItems(\EbaySdk\Api\Shopping\Types\GetMultipleItemsRequestType $request)
    {
        return $this->callOperation('GetMultipleItems', $request, '\EbaySdk\Api\Shopping\Types\GetMultipleItemsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetShippingCostsRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetShippingCostsResponseType
     */
    public function getShippingCosts(\EbaySdk\Api\Shopping\Types\GetShippingCostsRequestType $request)
    {
        return $this->callOperation('GetShippingCosts', $request, '\EbaySdk\Api\Shopping\Types\GetShippingCostsResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetSingleItemRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetSingleItemResponseType
     */
    public function getSingleItem(\EbaySdk\Api\Shopping\Types\GetSingleItemRequestType $request)
    {
        return $this->callOperation('GetSingleItem', $request, '\EbaySdk\Api\Shopping\Types\GetSingleItemResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GetUserProfileRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GetUserProfileResponseType
     */
    public function getUserProfile(\EbaySdk\Api\Shopping\Types\GetUserProfileRequestType $request)
    {
        return $this->callOperation('GetUserProfile', $request, '\EbaySdk\Api\Shopping\Types\GetUserProfileResponseType');
    }

    /**
     * @param \EbaySdk\Api\Shopping\Types\GeteBayTimeRequestType $request
     * @return \EbaySdk\Api\Shopping\Types\GeteBayTimeResponseType
     */
    public function geteBayTime(\EbaySdk\Api\Shopping\Types\GeteBayTimeRequestType $request)
    {
        return $this->callOperation('GeteBayTime', $request, '\EbaySdk\Api\Shopping\Types\GeteBayTimeResponseType');
    }
}
