<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Marketing\Enums;

/**
 *
 */
class CategoryScopeEnum
{
    const C_MARKETPLACE = 'MARKETPLACE';
    const C_STORE = 'STORE';
}
