<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Analytics\Types;

/**
 *
 * @property \EbaySdk\Api\Analytics\Types\Cycle $cycle
 * @property boolean $defaultProgram
 * @property string $evaluationReason
 * @property \EbaySdk\Api\Analytics\Types\Metric[] $metrics
 * @property \EbaySdk\Api\Analytics\Enums\ProgramEnum $program
 * @property \EbaySdk\Api\Analytics\Enums\StandardsLevelEnum $standardsLevel
 */
class StandardsProfile extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'cycle' => [
            'type' => 'EbaySdk\Api\Analytics\Types\Cycle',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'cycle'
        ],
        'defaultProgram' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'defaultProgram'
        ],
        'evaluationReason' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'evaluationReason'
        ],
        'metrics' => [
            'type' => 'EbaySdk\Api\Analytics\Types\Metric',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'metrics'
        ],
        'program' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'program'
        ],
        'standardsLevel' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'standardsLevel'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
