<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\ReturnManagement\Enums;

/**
 *
 */
class ReturnUserRoleType
{
    const C_BUYER = 'BUYER';
    const C_EBAY = 'EBAY';
    const C_OTHER = 'OTHER';
    const C_SELLER = 'SELLER';
    const C_SYSTEM = 'SYSTEM';
}
