<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\ReturnManagement\Enums;

/**
 *
 */
class StatusType
{
    const C_FAILED = 'FAILED';
    const C_SUCCESS = 'SUCCESS';
}
