<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Browse\Types;

/**
 *
 * @property \EbaySdk\Browse\Types\Image[] $additionalImages
 * @property string $categoryPath
 * @property string $description
 * @property \EbaySdk\Browse\Types\Image $image
 * @property string $itemGroupId
 * @property \EbaySdk\Browse\Types\ItemDigest[] $items
 * @property \EbaySdk\Browse\Types\ReviewRating $reviewRating
 * @property string $shortDescription
 * @property string $title
 * @property \EbaySdk\Browse\Types\TypedNameValue[] $variesByLocalizedAspects
 * @property \EbaySdk\Browse\Types\ErrorDetailV3[] $warnings
 */
class ItemGroup extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'additionalImages' => [
            'type' => 'EbaySdk\Browse\Types\Image',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'additionalImages'
        ],
        'categoryPath' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'categoryPath'
        ],
        'description' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'description'
        ],
        'image' => [
            'type' => 'EbaySdk\Browse\Types\Image',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'image'
        ],
        'itemGroupId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'itemGroupId'
        ],
        'items' => [
            'type' => 'EbaySdk\Browse\Types\ItemDigest',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'items'
        ],
        'reviewRating' => [
            'type' => 'EbaySdk\Browse\Types\ReviewRating',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'reviewRating'
        ],
        'shortDescription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shortDescription'
        ],
        'title' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'title'
        ],
        'variesByLocalizedAspects' => [
            'type' => 'EbaySdk\Browse\Types\TypedNameValue',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'variesByLocalizedAspects'
        ],
        'warnings' => [
            'type' => 'EbaySdk\Browse\Types\ErrorDetailV3',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'warnings'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
