<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Inventory\Types;

/**
 *
 * @property \EbaySdk\Inventory\Types\Availability $availability
 * @property \EbaySdk\Inventory\Enums\ConditionEnum $condition
 * @property string $conditionDescription
 * @property \EbaySdk\Inventory\Types\PackageWeightAndSize $packageWeightAndSize
 * @property \EbaySdk\Inventory\Types\Product $product
 * @property string $sku
 */
class InventoryItem extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'availability' => [
            'type' => 'EbaySdk\Inventory\Types\Availability',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'availability'
        ],
        'condition' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'condition'
        ],
        'conditionDescription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'conditionDescription'
        ],
        'packageWeightAndSize' => [
            'type' => 'EbaySdk\Inventory\Types\PackageWeightAndSize',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'packageWeightAndSize'
        ],
        'product' => [
            'type' => 'EbaySdk\Inventory\Types\Product',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'product'
        ],
        'sku' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sku'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
