<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace EbaySdk\Api\Fulfillment\Types;

/**
 *
 * @property boolean $ebaySupportedFulfillment
 * @property \EbaySdk\Api\Fulfillment\Types\Address $finalDestinationAddress
 * @property \EbaySdk\Api\Fulfillment\Enums\FulfillmentInstructionsType $fulfillmentInstructionsType
 * @property string $maxEstimatedDeliveryDate
 * @property string $minEstimatedDeliveryDate
 * @property \EbaySdk\Api\Fulfillment\Types\ShippingStep $shippingStep
 */
class FulfillmentStartInstruction extends \Plenty\Modules\Market\Ebay\Api\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ebaySupportedFulfillment' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ebaySupportedFulfillment'
        ],
        'finalDestinationAddress' => [
            'type' => 'EbaySdk\Api\Fulfillment\Types\Address',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'finalDestinationAddress'
        ],
        'fulfillmentInstructionsType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'fulfillmentInstructionsType'
        ],
        'maxEstimatedDeliveryDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'maxEstimatedDeliveryDate'
        ],
        'minEstimatedDeliveryDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minEstimatedDeliveryDate'
        ],
        'shippingStep' => [
            'type' => 'EbaySdk\Api\Fulfillment\Types\ShippingStep',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingStep'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[\Plenty\Modules\Market\Ebay\Api\Types\BaseType::class], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
